config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'

  devise_for :users, :controllers => { registrations: 'users/registrations' }
  authenticated :user do
    root :to => "users#profile", as: :user_profile
  end

  root :to => 'welcome#index'

  get 'users(:format)' => 'users#index', as: :users_list
  get 'user_requests(:format)' => 'users#requests', as: :requests
  get 'friends(:format)' => 'users#friends', as: :friends
  post 'users/:id/add_friend(:format)' => 'users#add_friend', as: :add_friend
  post 'users/:id/accept_request(:format)' => 'users#accept_request', as: :accept_request
  post 'users/:id/remove_friend(:format)' => 'users#remove_friend', as: :remove_friend
end

app/models/heading.rb
class Heading < ActiveRecord::Base
  belongs_to :user

  validates :user_id, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :headings
  has_friendship

  validates :name, presence: true
  validates :url, presence: true

  after_create :set_short_url
  after_create :add_headings

  def set_short_url
    ShortenUrlWorker.perform_async(self.id)
  end

  def add_headings
    AddHeadingsWorker.perform_async(self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :url])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = User.includes(:headings).find(current_user.id)
  end

  def index
    @current_user = current_user
    if params[:search].present?
      @users = User.where.not(id: current_user.id).where('name LIKE :search', search: "%#{params[:search]}%")
    else
      @users = User.where.not(id: current_user.id)
    end
  end

  def add_friend
    user = User.find_by(id: params[:id])
    current_user.friend_request(user)
    flash[:success] = "Request sent"
    redirect_to users_list_path
  end

  def requests
    @current_user = current_user
    @users = current_user.requested_friends
  end

  def accept_request
    user = User.find_by(id: params[:id])
    current_user.accept_request(user)
    flash[:success] = "Request accepted"
    redirect_to :back
  end

  def friends
    @users = current_user.friends
  end

  def remove_friend
    user = User.find_by(id: params[:id])
    current_user.remove_friend(user)
    flash[:success] = "Friend removed :("
    redirect_to :back
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Ruby on rails test for andOpen.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "andOpen", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Requests", requests_path %></li>
        <li><%= link_to "Friends", friends_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Search", users_list_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", root_path %></li>
              <li><%= link_to "Search", users_list_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
            <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Andopen</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>

app/views/users/friends.html.erb
<% if @users.present? %>
  <% @users.each do |user| %>
    <h3><%= user.name %></h3>
    <p> website: <a href="<%=user.short_url%>"><%=user.short_url%></a></p>
    <%= link_to "Remove friend", remove_friend_path(user), method: :post %>
  <% end %>
<%else%>
  <p>You have no firneds :(<p>
<% end %>

app/views/users/index.html.erb
<%= form_tag users_list_path, class: "form-inline", method: :get do %>
  <div class="row">
    <div class="input-group">
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "search. . .", autocomplete: "off" %>
      <span class="input-group-btn">
        <%= submit_tag "Search", class: "btn btn-primary" %>
      </span>
    </div>
  </div>
  <% if params[:query].present? %>
    <%= link_to "clear", patients_path %>
  <% end %>
<% end %>
<% if @users.present? %>
  <% @users.each do |user| %>
    <h3><%= user.name %></h3>
    <p> website: <a href="<%=user.short_url%>"><%=user.short_url%></a></p>
    <% if @current_user.friends_with?(user) %>
      <%= link_to "Remove friend", remove_friend_path(user), method: :post %>
    <% else %>
      <%= link_to "Add as Friend", add_friend_path(user), method: :post %>
    <% end %>
  <% end %>
<%else%>
  <p>No users exist<p>
<% end %>

app/views/users/profile.html.erb
<h2>Welcome to <%= @user.name %>'s Profile</h2>
<p>Website: <a href="<%=@user.url%>"> <%= @user.url %> </a></p>

<h2>Content of headings</h2>
<% @user.headings.each do |heading|%>
  <p><%= heading.content %></p>
<% end %>

app/views/users/requests.html.erb
<% if @users.present? %>
  <% @users.each do |user| %>
    <h3><%= user.name %></h3>
    <p> website: <a href="<%=user.short_url%>"><%=user.short_url%></a></p>
    <%= link_to "Accept Request", accept_request_path(user), method: :post %>
  <% end %>
<%else%>
 <p>You have no friend request :(<p>
<%end%>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<% if current_user %>
  <li><%= link_to "Sign out", destroy_user_session_path, method: :delete  %></li>
<% else %>
  <li><%= link_to "Sign up", new_user_registration_path %></li>
<% end %>